version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["server"]
    ports:
      - "5001:5000" 
    networks:
      - monitoring_network

  client:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["client"]
    depends_on:
      - server
    networks:
      - monitoring_network

networks:
  monitoring_network:
    driver: bridge
